// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: cluster.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCluster = `-- name: CreateCluster :one
INSERT INTO clusters (
  name,
  description
) VALUES (
 $1, $2
) RETURNING id, name, description, created_at, updated_at
`

type CreateClusterParams struct {
	Name        string `json:"name"`
	Description string `json:"description"`
}

func (q *Queries) CreateCluster(ctx context.Context, arg CreateClusterParams) (Cluster, error) {
	row := q.db.QueryRow(ctx, createCluster, arg.Name, arg.Description)
	var i Cluster
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAllClusters = `-- name: GetAllClusters :many
SELECT id, name, description, created_at, updated_at FROM clusters
`

func (q *Queries) GetAllClusters(ctx context.Context) ([]Cluster, error) {
	rows, err := q.db.Query(ctx, getAllClusters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Cluster{}
	for rows.Next() {
		var i Cluster
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCluster = `-- name: GetCluster :one
SELECT id, name, description, created_at, updated_at FROM clusters
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetCluster(ctx context.Context, id uuid.UUID) (Cluster, error) {
	row := q.db.QueryRow(ctx, getCluster, id)
	var i Cluster
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getClusterByName = `-- name: GetClusterByName :one
SELECT id, name, description, created_at, updated_at FROM clusters
WHERE name = $1 LIMIT 1
`

func (q *Queries) GetClusterByName(ctx context.Context, name string) (Cluster, error) {
	row := q.db.QueryRow(ctx, getClusterByName, name)
	var i Cluster
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCluster = `-- name: UpdateCluster :one
UPDATE clusters
SET
  name = COALESCE($1, name),
  description = COALESCE($2, description)
WHERE
  id = $3
  RETURNING id, name, description, created_at, updated_at
`

type UpdateClusterParams struct {
	Name        pgtype.Text `json:"name"`
	Description pgtype.Text `json:"description"`
	ID          uuid.UUID   `json:"id"`
}

func (q *Queries) UpdateCluster(ctx context.Context, arg UpdateClusterParams) (Cluster, error) {
	row := q.db.QueryRow(ctx, updateCluster, arg.Name, arg.Description, arg.ID)
	var i Cluster
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
