// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Agent struct {
	ID             uuid.UUID          `json:"id"`
	Name           string             `json:"name"`
	Token          string             `json:"token"`
	IsActive       bool               `json:"is_active"`
	Version        pgtype.Text        `json:"version"`
	CreatedAt      time.Time          `json:"created_at"`
	UpdatedAt      time.Time          `json:"updated_at"`
	LastConnection pgtype.Timestamptz `json:"last_connection"`
}

type Cluster struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type Node struct {
	ID         uuid.UUID `json:"id"`
	Name       string    `json:"name"`
	Ip         string    `json:"ip"`
	Os         string    `json:"os"`
	Arch       string    `json:"arch"`
	MacAddress string    `json:"mac_address"`
	Cpu        string    `json:"cpu"`
	Memory     string    `json:"memory"`
	Disk       string    `json:"disk"`
	ClusterID  uuid.UUID `json:"cluster_id"`
	IsActive   bool      `json:"is_active"`
	AgentID    uuid.UUID `json:"agent_id"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

type Session struct {
	ID           uuid.UUID `json:"id"`
	UserID       uuid.UUID `json:"user_id"`
	RefreshToken string    `json:"refresh_token"`
	UserAgent    string    `json:"user_agent"`
	ClientIp     string    `json:"client_ip"`
	IsBlocked    bool      `json:"is_blocked"`
	ExpiresAt    time.Time `json:"expires_at"`
	CreatedAt    time.Time `json:"created_at"`
}

type User struct {
	ID                uuid.UUID `json:"id"`
	Username          string    `json:"username"`
	HashedPassword    string    `json:"hashed_password"`
	FullName          string    `json:"full_name"`
	Email             string    `json:"email"`
	IsEmailVerified   bool      `json:"is_email_verified"`
	Role              string    `json:"role"`
	PasswordChangedAt time.Time `json:"password_changed_at"`
	CreatedAt         time.Time `json:"created_at"`
}
